name: Build Documentation
on:
    workflow_dispatch:
    push:
        branches:
          - 'main'
jobs:
    ci_doxygen:
        if: ${{github.ref_name}} == 'main'
        runs-on: ubuntu-latest
        steps:
            - name: Clone Repo
              shell: bash
              working-directory: ${{runner.workspace}}
              run: |
                git clone https://github.com/ORNL-Fusion/graph_framework ${{runner.workspace}}/graph_framework
                git clone https://token:${{secrets.AUTH_TOKEN}}@github.com/ORNL-Fusion/graph_framework-docs
            - name: Create build directory.
              shell: bash
              working-directory: ${{runner.workspace}}/graph_framework
              run: cmake -E make_directory build
            - name: Install Libraries Linux
              shell: bash
              run: |
                sudo apt update
                sudo apt-get install libnetcdf-dev
                sudo apt-get install doxygen
            - name: Configure CMake
              shell: bash
              working-directory: ${{runner.workspace}}/graph_framework/build
              run: cmake -DDOXYGEN_OUTPUT_DIRECTORY=${{runner.workspace}}/graph_framework-docs -DDOXYGEN_HTML_OUTPUT=docs ../
            - name: Build
              shell: bash
              working-directory: ${{runner.workspace}}/graph_framework/build
              run: make doc
            - name: Push changes.
              shell: bash
              working-directory: ${{runner.workspace}}/graph_framework-docs/docs
              env:
                GITHUB_TOKEN: ${{secrets.AUTH_TOKEN}}
              run: |
                git config user.name ${{secrets.AUTH_USER}}
                git config user.email ${{secrets.AUTH_EMAIL}}
                git add *
                git commit . -m "Update Doxygen docs."
                git push origin main --force

